import { keyBy } from "lodash-es";

/**
 * Id slugs for supported systems.
 */
export enum ZRomulatorSystemId {
  ThreeDo = "3do",
  Adam = "adam",
  Amiga = "amiga",
  Amiga1200 = "amiga1200",
  Amiga600 = "amiga600",
  AmigaCd32 = "amigacd32",
  AmstradCpc = "amstradcpc",
  Android = "android",
  Apple2 = "apple2",
  Apple2Gs = "apple2gs",
  Arcade = "arcade",
  Arcadia = "arcadia",
  Archimedes = "archimedes",
  Arduboy = "arduboy",
  Astrocde = "astrocde",
  Atari2600 = "atari2600",
  Atari5200 = "atari5200",
  Atari7800 = "atari7800",
  Atari800 = "atari800",
  AtariJaguar = "atarijaguar",
  AtariJaguarCd = "atarijaguarcd",
  AtariLynx = "atarilynx",
  AtariSt = "atarist",
  Atomiswave = "atomiswave",
  BbcMicro = "bbcmicro",
  C64 = "c64",
  CdiMono1 = "cdimono1",
  Cdtv = "cdtv",
  ChannelF = "channelf",
  Coco = "coco",
  Colecovision = "colecovision",
  Cps = "cps",
  Cps1 = "cps1",
  Cps2 = "cps2",
  Cps3 = "cps3",
  CrVision = "crvision",
  Daphne = "daphne",
  Dos = "dos",
  Dragon32 = "dragon32",
  Dreamcast = "dreamcast",
  EasyRpg = "easyrpg",
  Electron = "electron",
  Famicom = "famicom",
  FBA = "fba",
  FBNeo = "fbneo",
  FDS = "fds",
  FM7 = "fm7",
  FMTowns = "fmtowns",
  FPinball = "fpinball",
  Gamate = "gamate",
  GameAndWatch = "gameandwatch",
  GameCom = "gamecom",
  GameGear = "gamegear",
  GB = "gb",
  GBA = "gba",
  GBC = "gbc",
  GameCube = "gc",
  Genesis = "genesis",
  GMaster = "gmaster",
  GX4000 = "gx4000",
  Intellivision = "intellivision",
  LowResNx = "lowresnx",
  Lutro = "lutro",
  Macintosh = "macintosh",
  Mame = "mame",
  MameAdvMame = "mame-advmame",
  Mark3 = "mark3",
  MasterSystem = "mastersystem",
  MegaCd = "megacd",
  MegaDrive = "megadrive",
  MegaDriveJp = "megadrivejp",
  MegaDuck = "megaduck",
  MESS = "mess",
  Model2 = "model2",
  Model3 = "model3",
  MSX = "msx",
  MSX1 = "msx1",
  MSX2 = "msx2",
  MSXTurbor = "msxturbor",
  N3DS = "n3ds",
  Nintendo64 = "n64",
  N64DD = "n64dd",
  Naomi = "naomi",
  Naomi2 = "naomi2",
  NaomiGd = "naomigd",
  NDS = "nds",
  NeoGeo = "neogeo",
  NeoGeoCd = "neogeocd",
  NeoGeoCdJp = "neogeocdjp",
  Nintendo = "nes",
  NGage = "ngage",
  NeoGeoPocket = "ngp",
  NeoGeoPocketColor = "ngpc",
  Odyssey2 = "odyssey2",
  OpenBor = "openbor",
  Oric = "oric",
  Palm = "palm",
  PC = "pc",
  PC88 = "pc88",
  PC98 = "pc98",
  PcEngine = "pcengine",
  PcEngineCd = "pcenginecd",
  PCFx = "pcfx",
  Pico8 = "pico8",
  Plus4 = "plus4",
  PokeMini = "pokemini",
  PS2 = "ps2",
  PS3 = "ps3",
  PS4 = "ps4",
  PSP = "psp",
  PSVita = "psvita",
  PSX = "psx",
  PV1000 = "pv1000",
  SamCoupe = "samcoupe",
  Satellaview = "satellaview",
  Saturn = "saturn",
  SaturnJp = "saturnjp",
  ScummVM = "scummvm",
  SCV = "scv",
  Sega32X = "sega32x",
  SegaCd = "segacd",
  Sg1000 = "sg-1000",
  SGB = "sgb",
  SuperNintendo = "snes",
  Solarus = "solarus",
  SpectraVideo = "spectravideo",
  STV = "stv",
  Sufami = "sufami",
  SuperGrafx = "supergrafx",
  SuperVision = "supervision",
  SupraCan = "supracan",
  Switch = "switch",
  TgCd = "tg-cd",
  TG16 = "tg16",
  TI99 = "ti99",
  TIC80 = "tic80",
  TO8 = "to8",
  TRS80 = "trs-80",
  TypeX = "type-x",
  Uzebox = "uzebox",
  Vectrex = "vectrex",
  Vic20 = "vic20",
  VideoPac = "videopac",
  Vircon32 = "vircon32",
  VirtualBoy = "virtualboy",
  VPinball = "vpinball",
  VSmile = "vsmile",
  Wasm4 = "wasm4",
  Wii = "wii",
  WiiU = "wiiu",
  Windows = "windows",
  Windows3X = "windows3x",
  Windows9X = "windows9x",
  WonderSwan = "wonderswan",
  WonderSwanColor = "wonderswancolor",
  X1 = "x1",
  X68000 = "x68000",
  Xbox = "xbox",
  Xbox360 = "xbox360",
  XboxOne = "xboxone",
  ZMachine = "zmachine",
  Zx81 = "zx81",
  ZxSpectrum = "zxspectrum",
}

const ZRomulatorSystemIdMap = keyBy(Object.values(ZRomulatorSystemId));

/**
 * Gets whether a candidate string represents a system id.
 *
 * This check is case sensitive.
 *
 * @param candidate -
 *        The candidate to check.
 *
 * @returns
 *        True if candidate is a string that represents a system id.
 */
export function isSystemId(candidate: any): candidate is ZRomulatorSystemId {
  return (
    typeof candidate === "string" &&
    Object.prototype.hasOwnProperty.call(ZRomulatorSystemIdMap, candidate)
  );
}
